import type { WorkflowRun } from "@/types/workflow";

export const workflowRuns: WorkflowRun[] = [
  {
    id: "run_101",
    workflowKey: "lead-intake-to-review",
    title: "Lead intake to mock publish review",
    description:
      "Demonstrates intake planning, prompt compilation, evaluation, and a human gate before a publish-like action.",
    status: "waiting_for_approval",
    priority: "high",
    owner: "AI Platform",
    createdAt: "2026-06-15T08:00:00.000Z",
    updatedAt: "2026-06-15T08:18:00.000Z",
    agentIds: [
      "agent_intake_orchestrator",
      "agent_prompt_curator",
      "agent_eval_runner",
      "agent_approval_coordinator",
    ],
    promptIds: ["prompt_lead_triage_v3", "prompt_content_brief_v2", "prompt_eval_rubric_v1"],
    toolIds: [
      "tool_context_lookup",
      "tool_prompt_compiler",
      "tool_eval_runner",
      "tool_mock_publish",
    ],
    approvalIds: ["approval_run_101_publish"],
    evaluationIds: ["eval_run_101_triage"],
    metrics: {
      promptTokens: 6120,
      completionTokens: 2480,
      estimatedCostUsd: 0.84,
    },
    publicSafetyNote:
      "All artifacts are synthetic and every integration target is a mock:// destination.",
    trace: [
      {
        id: "step_101_1",
        name: "Parse workflow intake",
        agentId: "agent_intake_orchestrator",
        toolIds: ["tool_context_lookup"],
        status: "completed",
        startedAt: "2026-06-15T08:00:03.000Z",
        completedAt: "2026-06-15T08:00:08.000Z",
        durationMs: 5000,
        summary:
          "Normalised a mock lead request into a run plan and flagged the publish-like action as high risk.",
        inputArtifact: "Synthetic lead brief",
        outputArtifact: "Mock run plan",
        tokens: { promptTokens: 1180, completionTokens: 320 },
        costUsdEstimate: 0.13,
      },
      {
        id: "step_101_2",
        name: "Compile prompt packet",
        agentId: "agent_prompt_curator",
        toolIds: ["tool_prompt_compiler"],
        status: "completed",
        startedAt: "2026-06-15T08:00:09.000Z",
        completedAt: "2026-06-15T08:02:30.000Z",
        durationMs: 141000,
        summary:
          "Selected public-safe prompt versions and attached mock acceptance criteria for reviewer visibility.",
        inputArtifact: "Run plan",
        outputArtifact: "Prompt packet v3",
        tokens: { promptTokens: 1720, completionTokens: 760 },
        costUsdEstimate: 0.24,
      },
      {
        id: "step_101_3",
        name: "Run evaluation suite",
        agentId: "agent_eval_runner",
        toolIds: ["tool_eval_runner"],
        status: "completed",
        startedAt: "2026-06-15T08:10:00.000Z",
        completedAt: "2026-06-15T08:12:00.000Z",
        durationMs: 120000,
        summary:
          "Scored the output at 86/100 and warned that the approval summary should mention the high-risk tool.",
        inputArtifact: "Prompt packet v3",
        outputArtifact: "Triage Safety Suite result",
        tokens: { promptTokens: 2440, completionTokens: 980 },
        costUsdEstimate: 0.35,
      },
      {
        id: "step_101_4",
        name: "Wait for human approval",
        agentId: "agent_approval_coordinator",
        toolIds: ["tool_mock_publish"],
        status: "blocked",
        startedAt: "2026-06-15T08:15:00.000Z",
        summary:
          "Run is paused until a human approves the mock publish packet.",
        inputArtifact: "Evaluation result and publish packet",
        outputArtifact: "Pending approval",
        approvalId: "approval_run_101_publish",
        tokens: { promptTokens: 780, completionTokens: 420 },
        costUsdEstimate: 0.12,
      },
    ],
  },
  {
    id: "run_102",
    workflowKey: "operator-report-loop",
    title: "Operator report loop",
    description:
      "Shows a completed run that creates a reviewable briefing from anonymised sample activity signals.",
    status: "completed",
    priority: "medium",
    owner: "Operations",
    createdAt: "2026-06-14T14:40:00.000Z",
    updatedAt: "2026-06-14T15:22:00.000Z",
    agentIds: [
      "agent_intake_orchestrator",
      "agent_prompt_curator",
      "agent_eval_runner",
      "agent_trace_observer",
    ],
    promptIds: ["prompt_content_brief_v2", "prompt_eval_rubric_v1"],
    toolIds: ["tool_context_lookup", "tool_prompt_compiler", "tool_eval_runner", "tool_mock_notify"],
    approvalIds: ["approval_run_102_notify"],
    evaluationIds: ["eval_run_102_content"],
    metrics: {
      promptTokens: 4820,
      completionTokens: 1910,
      estimatedCostUsd: 0.62,
    },
    publicSafetyNote:
      "Activity signals are anonymised fixtures and notifications are never sent externally.",
    trace: [
      {
        id: "step_102_1",
        name: "Load sample activity signals",
        agentId: "agent_trace_observer",
        toolIds: ["tool_context_lookup"],
        status: "completed",
        startedAt: "2026-06-14T14:40:00.000Z",
        completedAt: "2026-06-14T14:42:00.000Z",
        durationMs: 120000,
        summary:
          "Read local mock activity signals and removed any customer-like detail from the briefing input.",
        inputArtifact: "Mock activity feed",
        outputArtifact: "Anonymised signal set",
        tokens: { promptTokens: 980, completionTokens: 280 },
        costUsdEstimate: 0.1,
      },
      {
        id: "step_102_2",
        name: "Draft operator report",
        agentId: "agent_prompt_curator",
        toolIds: ["tool_prompt_compiler"],
        status: "completed",
        startedAt: "2026-06-14T14:45:00.000Z",
        completedAt: "2026-06-14T14:52:00.000Z",
        durationMs: 420000,
        summary:
          "Produced a short operator report with actions, risks, and a mock handoff state.",
        inputArtifact: "Anonymised signal set",
        outputArtifact: "Operator report draft",
        tokens: { promptTokens: 2160, completionTokens: 910 },
        costUsdEstimate: 0.28,
      },
      {
        id: "step_102_3",
        name: "Evaluate report quality",
        agentId: "agent_eval_runner",
        toolIds: ["tool_eval_runner"],
        status: "completed",
        startedAt: "2026-06-14T15:00:00.000Z",
        completedAt: "2026-06-14T15:08:00.000Z",
        durationMs: 480000,
        summary:
          "Passed content quality at 94/100 with clear mock-data labelling.",
        inputArtifact: "Operator report draft",
        outputArtifact: "Content Quality Suite result",
        tokens: { promptTokens: 1680, completionTokens: 720 },
        costUsdEstimate: 0.24,
      },
      {
        id: "step_102_4",
        name: "Record approved notification",
        agentId: "agent_intake_orchestrator",
        toolIds: ["tool_mock_notify"],
        status: "completed",
        startedAt: "2026-06-14T15:18:00.000Z",
        completedAt: "2026-06-14T15:22:00.000Z",
        durationMs: 240000,
        summary:
          "Stored a fake operator notification after human approval. No message was sent.",
        inputArtifact: "Approved operator report",
        outputArtifact: "Mock notification record",
        approvalId: "approval_run_102_notify",
        tokens: { promptTokens: 0, completionTokens: 0 },
        costUsdEstimate: 0,
      },
    ],
  },
  {
    id: "run_103",
    workflowKey: "prompt-registry-review",
    title: "Prompt registry review",
    description:
      "Demonstrates a needs-changes path when the prompt packet is missing a public-safety boundary.",
    status: "needs_changes",
    priority: "medium",
    owner: "Prompt Ops",
    createdAt: "2026-06-14T11:30:00.000Z",
    updatedAt: "2026-06-14T12:16:00.000Z",
    agentIds: ["agent_prompt_curator", "agent_eval_runner", "agent_approval_coordinator"],
    promptIds: ["prompt_approval_summary_v1", "prompt_eval_rubric_v1"],
    toolIds: ["tool_prompt_compiler", "tool_eval_runner"],
    approvalIds: ["approval_run_103_prompt"],
    evaluationIds: ["eval_run_103_prompt"],
    metrics: {
      promptTokens: 3290,
      completionTokens: 1410,
      estimatedCostUsd: 0.43,
    },
    publicSafetyNote:
      "The run intentionally pauses because the mock prompt needs a clearer safety label.",
    trace: [
      {
        id: "step_103_1",
        name: "Review prompt metadata",
        agentId: "agent_prompt_curator",
        toolIds: ["tool_prompt_compiler"],
        status: "completed",
        startedAt: "2026-06-14T11:30:00.000Z",
        completedAt: "2026-06-14T11:38:00.000Z",
        durationMs: 480000,
        summary:
          "Found that the prompt status was draft and needed a stronger safety boundary before activation.",
        inputArtifact: "Approval Summary prompt metadata",
        outputArtifact: "Prompt review packet",
        tokens: { promptTokens: 1810, completionTokens: 620 },
        costUsdEstimate: 0.22,
      },
      {
        id: "step_103_2",
        name: "Evaluate approval readiness",
        agentId: "agent_eval_runner",
        toolIds: ["tool_eval_runner"],
        status: "completed",
        startedAt: "2026-06-14T11:45:00.000Z",
        completedAt: "2026-06-14T11:52:00.000Z",
        durationMs: 420000,
        summary:
          "Scored approval readiness at 72/100 and recommended changes before approval.",
        inputArtifact: "Prompt review packet",
        outputArtifact: "Approval Readiness Suite result",
        tokens: { promptTokens: 1480, completionTokens: 790 },
        costUsdEstimate: 0.21,
      },
      {
        id: "step_103_3",
        name: "Request prompt changes",
        agentId: "agent_approval_coordinator",
        toolIds: [],
        status: "blocked",
        startedAt: "2026-06-14T12:00:00.000Z",
        completedAt: "2026-06-14T12:16:00.000Z",
        durationMs: 960000,
        summary:
          "Human reviewer requested changes instead of approving activation.",
        inputArtifact: "Evaluation feedback",
        outputArtifact: "Needs-changes approval state",
        approvalId: "approval_run_103_prompt",
        tokens: { promptTokens: 0, completionTokens: 0 },
        costUsdEstimate: 0,
      },
    ],
  },
  {
    id: "run_104",
    workflowKey: "fail-closed-publish",
    title: "Fail-closed publish simulation",
    description:
      "Shows that a publish-like action is rejected when evaluation feedback has not been resolved.",
    status: "failed",
    priority: "high",
    owner: "AI Platform",
    createdAt: "2026-06-13T16:40:00.000Z",
    updatedAt: "2026-06-13T17:22:00.000Z",
    agentIds: ["agent_eval_runner", "agent_approval_coordinator"],
    promptIds: ["prompt_eval_rubric_v1"],
    toolIds: ["tool_eval_runner", "tool_mock_publish"],
    approvalIds: ["approval_run_104_publish"],
    evaluationIds: ["eval_run_104_publish"],
    metrics: {
      promptTokens: 2750,
      completionTokens: 1030,
      estimatedCostUsd: 0.35,
    },
    publicSafetyNote:
      "The run stops at a mock approval gate and never calls a real publishing system.",
    trace: [
      {
        id: "step_104_1",
        name: "Run platform readiness checks",
        agentId: "agent_eval_runner",
        toolIds: ["tool_eval_runner"],
        status: "completed",
        startedAt: "2026-06-13T16:40:00.000Z",
        completedAt: "2026-06-13T17:01:00.000Z",
        durationMs: 1260000,
        summary:
          "Evaluation failed because the mock publish step was sequenced before reviewer confidence was established.",
        inputArtifact: "Publish simulation packet",
        outputArtifact: "Platform Readiness Suite result",
        tokens: { promptTokens: 2750, completionTokens: 1030 },
        costUsdEstimate: 0.35,
      },
      {
        id: "step_104_2",
        name: "Reject mock publish",
        agentId: "agent_approval_coordinator",
        toolIds: ["tool_mock_publish"],
        status: "blocked",
        startedAt: "2026-06-13T17:05:00.000Z",
        completedAt: "2026-06-13T17:22:00.000Z",
        durationMs: 1020000,
        summary:
          "Human reviewer rejected the action, demonstrating fail-closed platform behaviour.",
        inputArtifact: "Failed evaluation result",
        outputArtifact: "Rejected approval state",
        approvalId: "approval_run_104_publish",
        tokens: { promptTokens: 0, completionTokens: 0 },
        costUsdEstimate: 0,
      },
    ],
  },
];
